---

- name: Server Package List
  set_fact:
    pkg_list:
      - vim
      - git
      - emacs
      - e2fsprogs
      - lustre-tests

- name: Server Packages
  yum: 
    name: "{{ pkg_list }}"
    state: present


- lineinfile:
    path: /etc/modprobe.d/lnet.conf
    line: 'options lnet networks="o2ib0(ib0)"'
    create: yes
