---
- hosts: mds0, oss1, c0, c1, oss0
  remote_user: root

  tasks:
  - name: Copying ntp conf file
    copy:
        src: /etc/ntp.conf
        dest: /etc/ntp.conf

  - name: install ntp
    yum:
        name: ntp
        state: latest
        update_cache: yes

  - name: start ntpd
    service:
        name: ntpd
        state: started
