---
- hosts: mds0, oss1, c0, c1, oss0
  remote_user: root

  tasks:
  - name: Copying pfstrased rpm
    copy:
        src: /root/rpmbuild/RPMS/x86_64/pfstrased-0.0.1-1.el7.x86_64.rpm
        dest: /tmp/pfstrased-0.0.1-1.el7.x86_64.rpm

  - name: remove pfstrase
    yum:
        name: pfstrased
        state: absent

  - name: install pfstrase
    yum:
        name: /tmp/pfstrased-0.0.1-1.el7.x86_64.rpm
        state: latest
        update_cache: yes

  - name: restart pfstrase
    service:
        name: pfstrase
        state: restarted
