---
- hosts: mds0, oss1, c0, c1, oss0
  remote_user: root

  tasks:
  - name: modify pfstrase conf file
    lineinfile: 
      path: /etc/pfstrase/pfstrase.conf
      regexp: '^frequency'
      line: 'frequency 20'
      state: present
    notify: reload pfstrase

  handlers:
  - name: reload pfstrase
    systemd:
        name: pfstrase
        state: reloaded
