---

- name: Client Packages
  yum: pkg={{item}} state=installed
  with_items:
    - vim
    - git
    - emacs
    - e2fsprogs
    - lustre-client


- lineinfile:
    path: /etc/modprobe.d/lnet.conf
    line: 'options lnet networks="o2ib0(ib0)"'
    create: yes
