---
- hosts: c0
  remote_user: root
  tasks:
  - name: set job 201 and user 3
    shell: 'echo {\"jid\" : \"201\", \"user\" : \"test3\"} | nc localhost 8888'
  - name: start io workload 1
    shell: echo 1 > /proc/sys/vm/drop_caches; /usr/lib64/compat-openmpi16/bin/mpirun -np 24 -wd /blue/testingdir /root/ior/bin/ior -t 4m -s 16 -b 32m -C -e

- hosts: c0, c1
  remote_user: root
  tasks:
  - name: reset job and user
    shell: 'echo {\"jid\" : \"-\", \"user\" : \"-\"} | nc localhost 8888'

- hosts: c0, c1
  remote_user: root
  tasks:
  - name: set job and user
    shell: 'echo {\"jid\" : \"301\", \"user\" : \"test4\"} | nc localhost 8888'

- hosts: c0
  remote_user: root
  tasks:
  - name: start io workload 2
    shell: echo 1 > /proc/sys/vm/drop_caches; /usr/lib64/compat-openmpi16/bin/mpirun -H c0,c1 -np 24 -wd /blue/testingdir /root/ior/bin/ior -t 4m -s 32 -b 32m -C -e

- hosts: c0,c1
  remote_user: root
  tasks:
  - name: reset job and user
    shell: '/usr/lib64/compat-openmpi16/bin/mpirun -H c0,c1 -np 2 echo {\"jid\" : \"-\", \"user\" : \"-\"} | nc localhost 8888'

- hosts: c1
  remote_user: root
  tasks:
  - name: set jid and uid
    shell: 'echo {\"jid\" : \"101\", \"user\" : \"test1\"} | nc localhost 8888'
  - name: start io workload 3
    shell: echo 1 > /proc/sys/vm/drop_caches; /usr/lib64/compat-openmpi16/bin/mpirun -np 2 -wd /blue/testingdir /root/ior/bin/ior -t 16m -s 8 -b 16m -C -e
  - name: reset job and user
    shell: 'echo {\"jid\" : \"-\", \"user\" : \"-\"} | nc localhost 8888'
