---
- hosts: c0
  remote_user: root
  tasks:
  - name: set job and user 1
    shell: 'echo {\"jid\" : \"101\", \"user\" : \"test1\"} | nc localhost 8888'
  - name: start io workload 1
    shell: watch -n 1 dd if=/dev/zero of=/blue/text1.txt count=1024 bs=1024 &

- hosts: c1
  remote_user: root
  tasks:
  - name: set job and user 2
    shell: 'echo {\"jid\" : \"102\", \"user\" : \"test2\"} | nc localhost 8888'
  - name: start io workload 2
    shell: watch -n 1 dd if=/dev/zero of=/blue/text2.txt count=1024 bs=4096
