# Generated by Django 2.1.5 on 2019-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obd',
            fields=[
                ('hostname', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nid', models.CharField(max_length=128, null=True)),
                ('jid', models.CharField(max_length=128, null=True)),
                ('user', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
