# Generated by Django 2.2.5 on 2020-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('hostname', models.CharField(max_length=128)),
                ('obdclass', models.CharField(max_length=128, null=True)),
                ('nid', models.CharField(max_length=128, null=True)),
                ('jid', models.CharField(max_length=128, null=True)),
                ('uid', models.CharField(max_length=128, null=True)),
                ('target', models.CharField(max_length=128, null=True)),
                ('client_nid', models.CharField(max_length=128, null=True)),
                ('server_nid', models.CharField(max_length=128, null=True)),
                ('stats_type', models.CharField(max_length=128, null=True)),
                ('event_name', models.CharField(max_length=128, null=True)),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'stats',
            },
        ),
    ]
