# Generated by Django 2.2.5 on 2019-11-22 20:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('time', models.DateTimeField(db_index=True, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=128)),
                ('nid', models.CharField(max_length=128, null=True)),
                ('jid', models.CharField(max_length=128, null=True)),
                ('uid', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_type', models.CharField(max_length=128, null=True)),
                ('target', models.CharField(max_length=128, null=True)),
                ('client_nid', models.CharField(max_length=128, null=True)),
                ('client_jid', models.CharField(max_length=128, null=True)),
                ('client_uid', models.CharField(max_length=128, null=True)),
                ('server_nid', models.CharField(max_length=128, null=True)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.Host')),
            ],
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='server',
        ),
    ]
