# Generated by Django 2.1.5 on 2019-04-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('hostname', models.CharField(max_length=128)),
                ('nid', models.CharField(max_length=128, null=True)),
                ('jid', models.CharField(max_length=128, null=True)),
                ('user', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurename', models.CharField(max_length=128, null=True)),
                ('value', models.FloatField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.devices')),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=128, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.hosts')),
            ],
        ),
        migrations.DeleteModel(
            name='obd',
        ),
        migrations.AddField(
            model_name='devices',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.stats'),
        ),
    ]
