# Generated by Django 2.2.5 on 2019-11-22 16:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0002_auto_20191122_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='obdclass',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
