# Generated by Django 3.1.6 on 2021-02-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0002_stats_fid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='client_nid',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='obdclass',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='server_nid',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='stats_type',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='target',
        ),
    ]
