# Generated by Django 2.1.5 on 2019-04-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0002_auto_20190405_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='measure',
            new_name='measures',
        ),
    ]
