# Generated by Django 2.2.5 on 2019-12-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0003_auto_20191122_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lod',
            fields=[
                ('time', models.DateTimeField(db_index=True, primary_key=True, serialize=False)),
                ('numobd', models.PositiveIntegerField(null=True)),
                ('activeobd', models.PositiveIntegerField(null=True)),
                ('blocksize', models.PositiveIntegerField(null=True)),
                ('filesfree', models.PositiveIntegerField(null=True)),
                ('filestotal', models.PositiveIntegerField(null=True)),
                ('kbytesfree', models.PositiveIntegerField(null=True)),
                ('tripetype', models.PositiveIntegerField(null=True)),
                ('kbytesavail', models.PositiveIntegerField(null=True)),
                ('kbytestotal', models.PositiveIntegerField(null=True)),
                ('lmv_failout', models.PositiveIntegerField(null=True)),
                ('stripecount', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mdt',
            fields=[
                ('time', models.DateTimeField(db_index=True, primary_key=True, serialize=False)),
                ('open', models.PositiveIntegerField(null=True)),
                ('close', models.PositiveIntegerField(null=True)),
                ('mknod', models.PositiveIntegerField(null=True)),
                ('mkdir', models.PositiveIntegerField(null=True)),
                ('statfs', models.PositiveIntegerField(null=True)),
                ('getattr', models.PositiveIntegerField(null=True)),
                ('setattr', models.PositiveIntegerField(null=True)),
                ('getxattr', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obdfilter',
            fields=[
                ('time', models.DateTimeField(db_index=True, primary_key=True, serialize=False)),
                ('read_bytes', models.PositiveIntegerField(null=True)),
                ('write_bytes', models.PositiveIntegerField(null=True)),
                ('create', models.PositiveIntegerField(null=True)),
                ('statfs', models.PositiveIntegerField(null=True)),
                ('set_info', models.PositiveIntegerField(null=True)),
                ('get_info', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sysinfo',
            fields=[
                ('time', models.DateTimeField(db_index=True, primary_key=True, serialize=False)),
                ('freeram', models.PositiveIntegerField(null=True)),
                ('totalram', models.PositiveIntegerField(null=True)),
                ('bufferram', models.PositiveIntegerField(null=True)),
                ('loadavg1m', models.FloatField(null=True)),
                ('loadavg5m', models.FloatField(null=True)),
                ('loadavg15m', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=128)),
                ('obdclass', models.CharField(max_length=16, null=True)),
                ('nid', models.CharField(max_length=128, null=True)),
                ('jid', models.CharField(max_length=128, null=True)),
                ('uid', models.CharField(max_length=128, null=True)),
                ('target', models.CharField(max_length=128, null=True)),
                ('client_nid', models.CharField(max_length=128, null=True)),
                ('server_nid', models.CharField(max_length=128, null=True)),
                ('stats_type', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.AddField(
            model_name='sysinfo',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.Tags'),
        ),
        migrations.AddField(
            model_name='obdfilter',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.Tags'),
        ),
        migrations.AddField(
            model_name='mdt',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.Tags'),
        ),
        migrations.AddField(
            model_name='lod',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfs_app.Tags'),
        ),
    ]
