# Generated by Django 2.1.5 on 2019-04-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0003_auto_20190405_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='id',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
