# Generated by Django 2.1.5 on 2019-04-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0004_auto_20190405_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='exports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('nid', models.CharField(max_length=128, null=True)),
                ('jid', models.CharField(max_length=128, null=True)),
                ('user', models.CharField(max_length=128, null=True)),
                ('measurename', models.CharField(max_length=128, null=True)),
                ('value', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='devices',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='measures',
            name='device',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='host',
        ),
        migrations.AddField(
            model_name='hosts',
            name='devicename',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='measurename',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='typename',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='devices',
        ),
        migrations.DeleteModel(
            name='measures',
        ),
        migrations.DeleteModel(
            name='stats',
        ),
        migrations.AddField(
            model_name='hosts',
            name='exports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pfs_app.exports'),
        ),
    ]
