# Generated by Django 2.2.5 on 2019-12-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0005_auto_20191203_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='obdfilter',
            name='punch',
            field=models.BigIntegerField(null=True),
        ),
    ]
