# Generated by Django 2.1.5 on 2019-04-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0006_auto_20190410_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('value', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exports',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='exports',
            name='value',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='value',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pfs_app.stats'),
        ),
        migrations.AddField(
            model_name='exports',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pfs_app.stats'),
        ),
    ]
