# Generated by Django 2.1.5 on 2019-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0007_auto_20190410_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='exports',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='value',
        ),
        migrations.AddField(
            model_name='hosts',
            name='event',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='export_host',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='export_jid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='export_nid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='export_user',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='stype',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
