# Generated by Django 2.1.5 on 2019-04-15 18:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0008_auto_20190410_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exports',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='device',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='event',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='export_host',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='export_jid',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='export_nid',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='export_user',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='stype',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='value',
        ),
        migrations.AddField(
            model_name='hosts',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='exports',
        ),
        migrations.DeleteModel(
            name='stats',
        ),
    ]
