# Generated by Django 2.1.5 on 2019-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfs_app', '0009_auto_20190415_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='obdclass',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
