---

- name: Common Package List
  set_fact:
    pkg_list:
      - autoconf
      - automake
      - libev-devel
      - librabbitmq-devel
      - pdsh

- name: Server Packages
  yum:
    name: "{{ pkg_list }}"
    state: present
